AllCops:
  TargetRubyVersion: 2.3
  Include:
  - "**/*.gemspec"
  - "**/Gemfile"
  Exclude:
  - "vendor/**/*"
  - "spec/**/*"
  - "features/**/*"
  - "db/schema.rb"
  - "*.gemspec"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
